language: ruby
sudo: false
services:
  - postgresql
  - mongodb
gemfile:
  - Gemfile
  - Gemfile.rails42
  - Gemfile.rails50
  - Gemfile.rails52
  - Gemfile.mongo_mapper
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby-9.1.14.0
before_install:
  # Rubygems > 3.0.0 no longer supported rubies < 2.3
  - gem install "rubygems-update:<3.0.0" --no-document && update_rubygems
  # Bundler 2.0 is not supported by Rails < 5
  - gem list -i bundler -v '>= 2.0.0' && rvm @global do gem uninstall bundler -x || true
  - gem install bundler -v '< 2'
env:
  global:
    - DB_USER=postgres
    - DB_PASS=
  matrix:
    - DB=sqlite3
    - DB=postgresql
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-9.1.14.0
  exclude:
    - gemfile: Gemfile.mongo_mapper
      env: DB=postgresql
branches:
  only:
    - master
notifications:
  email: false
