dist: focal
language: ruby
sudo: false
services:
  - mongodb
  - postgresql
gemfile:
  - Gemfile
  - Gemfile.rails60
  - Gemfile.mongo_mapper
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
before_install:
  - gem install bundler
env:
  global:
    - DB_USER=postgres
    - DB_PASS=
  matrix:
    - DB=sqlite3
    - DB=postgresql
matrix:
  fast_finish: true
  exclude:
    - gemfile: Gemfile.mongo_mapper
      env: DB=postgresql
branches:
  only:
    - master
notifications:
  email: false
