language: ruby
services:
  - mongodb
before_install:
  - gem install bundler
gemfile:
  - Gemfile
  - Gemfile.rails4
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
notifications:
  email:
    recipients:
      - lest@brainspec.com
      - nashby@brainspec.com
      - dreamfall@brainspec.com
