language: ruby
before_install:
  - gem install bundler
rvm:
  - 1.9.2
  - 1.9.3
gemfile:
  - gemfiles/Gemfile-ar-3.1.x
  - Gemfile
notifications:
  email:
    recipients:
      - sergey.nartimov@twinslash.com
      - vasily.ermolovich@twinslash.com
